name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ["bug"]
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: How to reproduce the bug
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: Please describe the expected behavior
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
    
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
      
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false

